[tool.poetry]
name = "eventum"
version = "0.1.0"
description = "Flexible event generation tool"
license = "Apache-2.0"
authors = ["Nikita Reznikov <nikita.reznikov.public@mail.ru>"]
readme = "README.md"
repository = "https://github.com/rnv812/Eventum"
keywords = ["generator", "testing", "data"]

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
pydantic = "^2.6.2"
setproctitle = "^1.3.3"
crontab = "^1.0.1"
numpy = "^1.26.4"
jinja2 = "^3.1.3"
keyring = "^24.3.1"
keyrings-cryptfile = "^1.3.9"


[tool.poetry.group.studio.dependencies]
streamlit = "^1.28.1"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pytest = "^8.0.1"
matplotlib = "^3.8.3"
pyright = "^1.1.354"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
eventum = "eventum.cli.__main__:main"
eventum-studio = "eventum.studio.__main__:main"
