[tool.poetry]
name = "eventum-core"
version = "1.0.0"
description = "Flexible event generator"
license = "Apache-2.0"
authors = ["Nikita Reznikov <nikita.reznikov.public@mail.ru>"]
readme = "README.md"
repository = "https://github.com/Eventum-Generatives/EventumCore"
documentation = "https://eventum-generatives.github.io/Website/"
keywords = ["generator", "testing", "data", "event"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Traffic Generation"

]
packages = [
    {include = "core"}
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.6.2"
setproctitle = "^1.3.3"
numpy = "^1.26.4"
jinja2 = "^3.1.3"
keyring = "^24.3.1"
keyrings-cryptfile = "^1.3.9"
alive-progress = "^3.1.5"
aiohttp = {extras = ["speedups"], version = "^3.9.3"}
aiofiles = "^23.2.1"
croniter = "^2.0.5"
eventum-content-manager = "^1.0.2"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pytest = "^8.0.1"
mypy = "^1.9.0"
types-aiofiles = "^23.2.0.20240403"
types-croniter = "^2.0.0.20240423"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
