[tool.poetry]
name = "eventum-app"
version = "1.0.0"
description = "Flexible event generator"
license = "Apache-2.0"
authors = ["Nikita Reznikov <nikita.reznikov.public@mail.ru>"]
readme = "README.md"
repository = "https://github.com/rnv812/Eventum"
documentation = "https://rnv812.github.io/Eventum"
keywords = ["generator", "testing", "data", "event"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Traffic Generation"

]
packages = [
    {include = "eventum"}
]

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
pydantic = "^2.6.2"
setproctitle = "^1.3.3"
numpy = "^1.26.4"
jinja2 = "^3.1.3"
keyring = "^24.3.1"
keyrings-cryptfile = "^1.3.9"
alive-progress = "^3.1.5"
pandas = "^2.2.1"
aiohttp = {extras = ["speedups"], version = "^3.9.3"}
aiofiles = "^23.2.1"
croniter = "^2.0.5"


[tool.poetry.group.studio.dependencies]
streamlit = "^1.28.1"
plotly = "^5.20.0"
streamlit-elements = "^0.1.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pytest = "^8.0.1"
mypy = "^1.9.0"
types-python-crontab = "^3.0.0.20240106"
types-pyyaml = "^6.0.12.20240311"
pandas-stubs = "^2.2.1.240316"
types-aiofiles = "^23.2.0.20240403"
types-croniter = "^2.0.0.20240423"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
eventum = "eventum.cli.__main__:main"
eventum-studio = "eventum.studio.__main__:main"
