input:
  patterns:
    - test.yaml
    - test2.yaml
  timestamps:
    - "2024-02-15T12:00:00.000Z"
    - "2024-02-16T12:00:00.000Z"
    - "2024-02-17T12:00:00.000Z"
  cron:
    expression: "*/5 * * * *"
    count: 3
  sample:
    count: 100

event:
  params: { }

  samples:
    users:
      type: csv
      header: true
      delimiter: ","
      source: user.csv
    hosts:
      type: items
      source:
        - host1
        - host2
  
  mode: all | any | chance | spin
  templates:
    windows4624:
      codec: json
      chance: 9
    windows4625:
      codec: json
      chance: 1

  subprocesses:
    abnormal_activity:
      config: example2.yaml
      detach: true

output:
  opensearch:
    host: localhost
    port: 9200
    user: admin
    password: "{{password}}"
