input:
  patterns:
    - "test.yml"
  # cron:
  #   expression: "* * * * *"
  #   count: 1

event:
  params: { }
  
  samples:
    hosts:
      type: items
      source:
        - host1
        - host2
        - host3
        - host4
        - host5
        - host6
        - host7
  
  mode: all
  templates:
    windows4624:
      template: host_cpu.json.jinja
      chance: 1
    # windows4625:
    #   template: host_mem.json.jinja
    #   chance: 1

  subprocesses: { }

output:
  file:
    path: /home/nikita/log.log
    format: json-lines
