input:
  patterns:
    - "test.yml"
  # cron:
  #   expression: "* * * * *"
  #   count: 1

event:
  params: { }
  
  samples:
    hosts:
      type: items
      source:
        - host1
        - host2
  
  mode: chance
  templates:
    windows4624:
      template: test.json.jinja
      chance: 1
    windows4625:
      template: test.json.jinja
      chance: 2

  subprocesses: { }

output:
  file:
    path: /home/nikita/test.log
    format: json-lines
