input:
  # time_patterns:
  #   - "test.yml"
  # cron:
  #   expression: "* * * * *"
  #   count: 1
  # timer:
  #   seconds: 1
  #   count: 1
  #   repeat: true
  sample:
    count: 10
  # linspace:
  #   start: '2024-05-01T00:00:00'
  #   end: '2024-05-01T00:00:00'
  #   count: 31 

event:
  params: { }
  
  samples:
    hosts:
      type: items
      source:
        - host1
        - host2
        - host3
        - host4
        - host5
        - host6
        - host7
  
  mode: all
  templates:
    windows4624:
      template: host_cpu.json.jinja
      chance: 1
    # windows4625:
    #   template: host_mem.json.jinja
    #   chance: 1

output:
  - stdout:
      format: json-lines
